### ISSUE TITLE
Update Firebase to v3

### ISSUE THREAD

**Issue by kevinkace** [tivac/anthracite#112]
https://firebase.google.com/support/guides/firebase-web

**Comment by tivac** [comment]
Free for the taking, will be a bit before I can get to it!

**Comment by tivac** [comment]
Working on this in the [firebase-3](https://github.com/tivac/anthracite/tree/firebase-3) branch.

**Comment by tivac** [comment]
### TODO

- [ ] Figure out how to make auth work w/ my current route wrapper
- [ ] Make sure JWT auth still works
- [ ] Probably implement FB/GOOG auth while I'm in there

**Comment by tivac** [comment]
Adjusting scope, because it'll require some non-trivial changes to JsSrv to support the higher encryption requirements in Firebase@3's JWT implementation.

**Comment by mooreds** [comment]
FYI. this is now blocking any new sites on crucible.

**Comment by tivac** [comment]
Open to a PR for this, I'm not actively working on Crucible any more. :-\
